stages:
  - Test

variables:
  #Space seperated ansible roles required to deploy application.
  CI_ROLES: spring-boot consul-service vault-secrets
  CI_SERVICE_AREA: corporate
  CI_SERVICE_NAME: comp-man
  CI_APP_NAME: comp-man
  CI_TAG_ROLE: tag_Role_CMS_Application_Server
  CI_DEV_URL: http://dev-comp-man.service.nhsbsa:3000/compman
  CI_SELENIUM_HUB: http://DPS-COR-SHA-TST-TST01.node.nhsbsa:4444/wd/hub
  POSTGRES_DB: cems_pgdb
  POSTGRES_USER: liquibase_user
  POSTGRES_PASSWORD: runner

test binary:
 stage: Test
 
 artifacts:
    name: "HtmlReport_${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
    - target/jsonReports/${testType}/
 
 script:
   # Test binary step
   - mvn clean verify -Dcucumber.options="src/test/resources/features/Cloud --tags @smoke --no-dry-run" -Denv=ci -Dbrowser=chrome_grid -Dgridhostname=${CI_SELENIUM_HUB}
 tags:
   - test

regression test binary:
  stage: Test
  when: manual
  script:
    # Test binary step
  - mvn clean verify -Dcucumber.options="src/test/resources/features/Cloud --tags @regression --no-dry-run" -Denv=ci -Dbrowser=chrome_grid -Dgridhostname=${CI_SELENIUM_HUB}
  tags:
    - test
